apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: componentb-devfile-sample-go-basic-private-devfile-nested-cio7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-shnq-tenant/mc-golang-nested/componentb-devfile-sample-go-basic-private-devfile-nested-cio7@sha256:f4fef06994f01a677e6a44709b20cf8d53f57fc0638eb5adf2ab6f4a3cacefc8
        name: my-go
        resources: {}
status: {}
